name: Run PyTorch Tests

on:
  workflow_call:
    inputs:
      torch-version:
        required: true
        type: string

jobs:
  run-pytorch-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          sed -i 's/mct-quantizers/mct-quantizers-nightly/' requirements.txt
          python -m pip install --upgrade pip
          pip install -r requirements.txt          
          pip install torch==${{ inputs.torch-version }} torchvision onnx onnxruntime
      - name: Run unittests
        run: python -m unittest discover tests/pytorch_tests -v




